const { test } = require('node:test');
const assert = require('node:assert/strict');
process.env.DATABASE_URL = 'postgresql://test:test@localhost:5432/test';
process.env.JWT_SECRET = 'integration-test-only-secret';
process.env.DOTENV_CONFIG_QUIET = 'true';
const { createApp } = require('../dist/app');
const { prisma } = require('../dist/config/prisma');
const { signToken } = require('../dist/utils/jwt');

// Exercise real HTTP routing and JWT middleware with an isolated persistence double.
test('authenticated education API and classroom permissions', async (t) => {
  const server = createApp().listen(0, '127.0.0.1');
  await new Promise(resolve => server.once('listening', resolve));
  t.after(() => new Promise(resolve => server.close(resolve)));
  t.after(() => prisma.$disconnect());
  const base = `http://127.0.0.1:${server.address().port}`;
  const user = { id: 'teacher-a', role: 'PROFESSOR' };
  let where;
  prisma.user.findUnique = async () => user;
  prisma.user.findUniqueOrThrow = async () => user;
  prisma.classroom.findMany = async (args) => { where = args.where; return []; };
  prisma.material.findMany = async () => [];
  prisma.glossary.findMany = async () => [];
  const token = signToken({ sub: user.id, email: 'test@example.com' });
  const request = (path, method = 'GET', body, authenticated = true) => fetch(base + path, { method, headers: { 'Content-Type': 'application/json', ...(authenticated ? { Authorization: `Bearer ${token}` } : {}) }, body: body === undefined ? undefined : JSON.stringify(body) });
  assert.equal((await request('/education', 'GET', undefined, false)).status, 401);
  assert.equal((await fetch(base + '/education', { headers: { Cookie: 'festival_session=%ZZ' } })).status, 401);
  const response = await request('/education');
  assert.equal(response.status, 200);
  assert.deepEqual(await response.json(), { classrooms: [], students: [], lessons: [], materials: [], terms: [] });
  assert.deepEqual(where, { OR: [{ teacherId: 'teacher-a' }, { members: { some: { userId: 'teacher-a' } } }] });
  const room = { id: 'room-a', name: 'Sala real', description: null, code: 'ABC-123', teacher: { name: 'Docente', teacherProfile: { discipline: 'História' } }, members: [{ userId: 'student-a', joinedAt: new Date(), user: { id: 'student-a', name: 'Aluno', role: 'ALUNO' } }], lessons: [{ id: 'lesson-a', title: 'Aula', createdAt: new Date(), status: 'AGENDADA', summary: { content: 'Resumo salvo' }, transcriptionSessions: [{ transcript: 'Texto salvo' }] }] };
  prisma.classroom.findMany = async () => [room];
  const populated = await (await request('/education')).json();
  assert.equal(populated.classrooms[0].id, 'room-a');
  assert.deepEqual(populated.students[0].classroomIds, ['room-a']);
  assert.equal(populated.lessons[0].status, 'scheduled');
  assert.equal(populated.lessons[0].transcript, 'Texto salvo');
  assert.equal(populated.lessons[0].summary, 'Resumo salvo');
  assert.equal(JSON.stringify(populated).includes('passwordHash'), false);
  let updated = false;
  prisma.classroom.findUnique = async () => ({ id: 'room-b', teacherId: 'teacher-b' });
  prisma.classroom.update = async () => { updated = true; };
  assert.equal((await request('/education/classrooms/room-b', 'PATCH', { name: 'Turma B' })).status, 403);
  assert.equal(updated, false);
  prisma.classroom.findUnique = async () => ({ id: 'room-a', teacherId: 'teacher-a' });
  assert.equal((await request('/education/classrooms/room-a', 'PATCH', { name: 'x' })).status, 400);
  assert.equal((await request('/education/classrooms/room-a', 'PATCH', { name: 'Turma A', description: 'Descrição' })).status, 204);
  assert.equal(updated, true);
  let membership;
  prisma.classroomMember.upsert = async args => { membership = args; return {}; };
  assert.equal((await request('/education/join', 'POST', { code: ' abc-123 ' })).status, 200);
  assert.equal(membership.create.userId, 'teacher-a');
  assert.deepEqual(membership.update, {});
  prisma.classroom.findUnique = async () => null;
  assert.equal((await request('/education/join', 'POST', { code: 'missing' })).status, 404);
  user.role = 'ALUNO';
  assert.equal((await request('/classrooms', 'POST', { name: 'Turma' })).status, 403);
  user.role = 'PROFESSOR';
  let saved;
  prisma.classroom.create = async args => { saved = args.data; return { id: 'room-new', ...args.data, members: [], lessons: [], createdAt: new Date() }; };
  const created = await request('/classrooms', 'POST', { name: 'Nova turma', description: 'Descrição persistida' });
  assert.equal(created.status, 201);
  assert.equal(saved.teacherId, user.id);
  assert.equal(saved.description, 'Descrição persistida');
  assert.ok((await created.json()).classroom.code);
});
